### ISSUE TITLE
Version 3.1.8: Edit-Text causing button text to split into multiple lines

### ISSUE THREAD

**Issue by calebpeffer** [addisonElliott/SegmentedButton#29]
Hello,

I found a strange bug with the latest release. When I edit the text of an editText in the same activity as a segmentedButtonGroup, the last character of the text in each of the segmented buttons is pushed to a new-line.

(API level 29)

**Reverting to version 3.1.7 solved this issue.**

Please let me know if you would like me to share the relevant XML

**Comment by addisonElliott** [comment]
Hello.

Yes, if you can please share any relevant code with me. I'll try to reproduce it.

This seems very odd since very little changed between v3.1.7 and v3.1.8. See here: https://github.com/addisonElliott/SegmentedButton/compare/3.1.7...3.1.8

**Comment by vcoolish** [comment]
It also happens after rotation. Can I pull request with a set lines count feature for static layout? It will be very helpful. Also ellipsize feature would be helpful in most cases

**Comment by addisonElliott** [comment]
Sure! That sounds reasonable to me. Thank you
