### ISSUE TITLE
Selector with bordered radius

### ISSUE THREAD

**Issue by vinzaceto** [addisonElliott/SegmentedButton#4]
In the base code there is a sample with a selector having bordered radius. Is it possible to implement this feature? At this moment the selector has rectangular shape

**Comment by addisonElliott** [comment]
The screenshots on the README are from the old library, but I did implement all features from the old library in this library.

So yes, you **should** be able to. Let me know if you are having trouble and I'll test it on my end.

**Comment by addisonElliott** [comment]
Going to spend this weekend working on the PR. If you have a screenshot/sample I can go off of, that would be helpful.

**Comment by addisonElliott** [comment]
Functionality added for rounded corners on the selected button as well as a border.

Please upgrade to v3.1.1.

**Note:** `app:background` was switched to `android:background` in v3.1.1.
